ALTER TABLE LISTE_ATTENTE
ADD CONSTRAINT FK_LISTATTENTE_ATTENTE FOREIGN KEY(num_attente)
REFERENCES ATTENTE(num_attente);

ALTER TABLE ATTENTE
ADD CONSTRAINT FK_ATTENTE_UTI FOREIGN KEY(id_uti)
REFERENCES UTILISATEUR(id_uti);

ALTER TABLE ATTENTE
ADD CONSTRAINT FK_ATTENTE_PLACE FOREIGN KEY(num_place)
REFERENCES PLACE(num_place);